### ISSUE TITLE
RFC: Add functionality to inline duplicate content across markdown files

### ISSUE THREAD

**Issue by ynx0** [urbit/urbit.org#1299]
In a recent PR (#1295), I fixed a spelling bug between two sections with identical contents replicated manually on two separate pages. Now, this wasn't really a big deal, but I feel like these kinds of mistakes, along with the hassle of constantly updating the relevant sections, could be mitigated by some kind of "markdown include" functionality. However, a cursory search about including markdown files from other markdown files doesn't seem to be supported in nextjs. I did stumble upon [Paradox](https://developer.lightbend.com/docs/paradox/current/directives/includes.html), which has this kind of functionality and quite frankly a lot more, but migrating the whole documentation system would require a lot more impetus than just this. I'd love to hear thoughts about how this could be resolved, if it seems like a reasonable enough issue.

<br/>

Pages with duplicate content in question:
- https://urbit.org/docs/userspace/gall-guide
- https://urbit.org/docs/userspace/gall-guide/intro

**Comment by matildepark** [comment]
Transclusions are way useful and cool; there's a few ways we could do this — I would honestly be surprised if there wasn't a remark plugin for this?

Nextjs tends to prefer [MDX](https://nextjs.org/docs/advanced-features/using-mdx) which [also has transclusion](https://nicedoc.io/mdx-js/specification#mdx-transclusion).

I think we would probably plan a docs overhaul where we'd dictate product features and renovate the docs section of the site wholesale; it's just porting older urbit.org TOML and the like.

**Comment by matildepark** [comment]
This is becoming a little long in the tooth — we're starting to incorporate more dynamic content inside pages, as well as duplicate content and components, and I think we're going to have to undertake MD -> MDX migration as a whole kinda soon. It would let us keep a lot of content current in a saner way. Putting it on the list...

**Comment by matildepark** [comment]
Current plan is to use [Markdoc](https://markdoc.io). Timeline indeterminate but Soon (™)

**Comment by ynx0** [comment]
@matildepark funny, just saw that on HN the other day and thought it looked pretty good. How much work does it look like to get started with it plus migration work?

**Comment by matildepark** [comment]
- I'm basically going to have to migrate us from TOML to YAML. I can do this by writing a script to walk all our files and process them like we already do, then remove the TOML lines and output the processed metadata in YAML format at the top of each file.
- I will have to restructure our Markdown build engine for it. It would probably end up being client-side Markdown (#1471) since that's how Markdoc's docs are written. This means our syntax highlighting is a gigantic question mark. However, since the Markdoc renderer is separate from its Remark cousins, we can possibly shove code blocks into prism in a more bespoke way? It requires some research. Worst comes to worst, we're outputting React on back-end and using ReactDOM.render() where we currently output straight HTML in components/Markdown.js. This would probably end up addressing #1358.
- Markdown.js would look completely different; we'd probably do `withMarkdoc()` against the site to start, if syntax highlighting regresses we might have to restructure Markdoc as a static site generated HTML thing instead of client-side.
- We'd begin componentising common elements and introducing them afterward.
