### ISSUE TITLE
click to access non-bottom-level pages on collapsible sidebar

### ISSUE THREAD

**Issue by drbeefsupreme** [urbit/urbit.org#258]
As far as I can tell, there is no way to access the non-bottom-level pages on the collapsible sidebar by clicking. So this makes content such as `https://urbit.org/docs/tutorials/`, `https://urbit.org/docs/reference/`, `https://urbit.org/docs/tutorials/arvo/` inaccessible via the sidebar.

I've tried to find a way to do this with Brave and Firefox.

These pages are still accessible via the Search bar, but I think we need some way to incorporate that into the collapsible sidebar as well.

**Comment by matildepark** [comment]
This was actually on purpose! Our previous directive was that those index pages were essentially pointless. I made the Table of Contents for the standard library because the page was basically not accessible otherwise.

I _think_ you can nest `<a>` elements within `<summary>` elements? I would have to see. But then you might find the collapsed nav would itself hit the link instead of unfold. We could also alternatively just add an index page to all these as the first item in the list.

I believe this call rests with @rmariani.

**Comment by drbeefsupreme** [comment]
I agree that a lot of them are useless, but some of them are not, e.g. `https://urbit.org/docs/tutorials/arvo/`. So maybe we should move the useful ones into bottom level pages? Will talk about this at meeting today.

**Comment by matildepark** [comment]
Most relevant discussion here is #713, this refers to an older iteration of the site.
