### ISSUE TITLE
Landing page has too many links and doesn’t funnel a large enough % of traffic onto the blog

### ISSUE THREAD

**Issue by tacryt-socryp** [urbit/urbit.org#356]
Anyone want to discuss ways to improve this experience?

**Comment by matildepark** [comment]
I've suggested this in several analytics reports recently. I will provide suggestions anon.

**Comment by tacryt-socryp** [comment]
Thanks Matilde. I wanted to log this because it’s implicitly been an issue.

**Comment by matildepark** [comment]
OK.

1. We need to surface latest update and latest blog post on the homepage. Early drafts of the new urbit.org had these.
a. By surfacing them this way, we don't necessarily need to have them *again* on the landing page; they exist in the footer as such. So optionally, remove the "Learn more" section entirely from the landing page and make "stay up to date" a full-width section at the end again. Make the "latest update" and "latest blog" headers links.

2. We should deprioritise specific pages on the landing page that already exist on the footer and are a bit specific: I'm thinking /media, Grants, Hoon School. Encourage exploration of the site map in the footer for people who are already "in".

3. Since it's for introductory users, Understanding Urbit should be a single link to the introduction, not six links in its own box. It does its job one time, and then each visit it's essentially in the way. Return visits want to see, quickly, if some updated section content is new.

I'm the closest thing Urbit.org has to an owner, but @galenwp gets the call on things like this.

**Comment by galenwp** [comment]
I'd be perfectly happy to see the most recent post on the homepage

**Comment by tacryt-socryp** [comment]
Matilde, I love all three of your suggestions.
