### ISSUE TITLE
Add permalink to the latest version of the AArch64 static binary

### ISSUE THREAD

**Issue by cxk280** [urbit/urbit.org#540]
AWS recently introduced [Graviton2-based EC2 instances](https://aws.amazon.com/ec2/graviton/), and these are now the most cost-efficient way to run Urbit on AWS. However, these instances require the AArch64 static binary. Can someone set up a permalink to the most recent version of this, as was done with `linux64` (`https://urbit.org/install/linux64/latest`)? So far I've been downloading it as described [here](https://botter-nidnul.github.io/AArch64_Urbit_Static_Binaries.html), but I cannot ensure the latest version is being downloaded this way.

**Comment by ohAitch** [comment]
How long until an open linux Rosetta-alike makes them also the most
cost-efficient way to run x86 workloads… RIP intel

**Comment by matildepark** [comment]
It's an easy add on urbit.org — but we don't supply the arm64 binaries on urbit/urbit. We should do that first, which I think has its own issue.

**Comment by cxk280** [comment]
Where does this stand?

**Comment by matildepark** [comment]
Nobody is working on arm64 builds as part of the process as far as I know. @botter-nidnul any idea how that worked?

**Comment by botter-nidnul** [comment]
The last thing I heard about urbit/urbit aarch64 builds [was this](https://github.com/urbit/urbit/pull/2535#issuecomment-714577605) - basically, urbit-king makes aarch64 builds complicated because it can't be cross compiled on x86. Otherwise the new build system is great, and static aarch64 binaries don't require the cumbersome patch set they used to. I'm not aware of any further work done to get aarch64 into CI, though.

If you're running something debian based on AWS @cxk280, my [apt repository](https://botter-nidnul.github.io/Urbit_AArch64_APT_Repository.html) can automatically provide you the latest version. I'm planning to keep the contents of that package the same as what urbit/urbit delivers (just in aarch64), although I did add `setcap 'cap_net_bind_service=+ep'` to the postinst script for convenience, which might not be appropriate with your setup.

**Comment by botter-nidnul** [comment]
I tried creating a redirect at https://botter-nidnul.github.io/latest_redirect but I'm not sure how to get wget or curl to follow that redirect because it's not header based, and meta tags are the best I can do on github.io

**Comment by cxk280** [comment]
@botter-nidnul Do you have another domain you can put it on that does handle header-based redirects?

**Comment by cxk280** [comment]
The following shell script will do it:

```
curl -L botter-nidnul.github.io/latest_redirect -o output.txt
xmllint --html --xpath //a/@href output.txt | sed 's/ href="\([^"]*\)"/\1\n/g' > downloadlink.txt
xargs -n 1 curl -OL < downloadlink.txt
rm output.txt downloadlink.txt
tar xzf *.tar.gz
```

This issue is solved so I will close it.

**Comment by cxk280** [comment]
@botter-nidnul (Can you just make sure you keep the binary at that link current?)

**Comment by botter-nidnul** [comment]
yeah, I should see that file everytime I update that repository, and that should be enough to remind me🤞

**Comment by cxk280** [comment]
Wonderful, thank you. This saves me a lot of effort.
