### ISSUE TITLE
Are recent post dates correct?

### ISSUE THREAD

**Issue by jtobin** [urbit/urbit.org#57]
Just noticed that the dates seem kind of weird in recent posts on the website:

![](https://dsh.re/c881d)

Note `~2019.3.14 updates` is followed by `~2019.3.4`, and similarly for the next entry.

Is this intentional?  I was thinking that the headers were supposed to act as like week or two-week long containers or something, but there seems to be no structure to them.

**Comment by flowerornament** [comment]
The title `~[date] Update` refers to the week the content refers to, while the date tag refers to the date that the content was posted to the website.

So, on March 14th we posted an update referring to the week of March 4th.

This is something I inherited and you're the second person today to be confused by it. I could be convinced to do something else if you think it would be better!

**Comment by jtobin** [comment]
Ok, I think the overall structure makes sense.  It probably just seems a little weird for these posts in particular because the tag dates are separated from the title dates by like 10 days.  Further back the dates in the tag & header are identical.

When I think about it, It's probably better to just use the same date in both.  "A short update from the Tlon team for the week of X" can safely be interpreted as "this is the update we're posting on the week that X falls into."  It doesn't need to be *about* any week in particular, since really it's just going to be about what we've been up to lately, anyway.

**Comment by flowerornament** [comment]
@jtobin seems fine to me. I may have been a bit pedantic – "from the week of of [date]" to me means precisely "from the week that started on [date] (be it the Sunday or the Monday)". I opted for the current system because having weekly updates be dated to the day they're posted would involve also changing all of the descriptions of the previous weekly updates so that that sentence remained accurate.

I'll fix this in the upcoming website revamp.

**Comment by jtobin** [comment]
No I hear you, that's definitely my primary reading too.  But I think the alternative reading is also acceptable, and nixes the date weirdness. 😄
