### ISSUE TITLE
Ford runes exist in glossary but direct to dead links

### ISSUE THREAD

**Issue by ynx0** [urbit/urbit.org#578]
I was trying to figure out what some runes like `/-` and `/+` did using the [glossary](https://github.com/urbit/urbit.org/blob/master/static/glossary.js#L900) (which is really helpful btw). However, all of the runes lead to now removed documentation (i.e. results in a 404).

**Comment by matildepark** [comment]
Cc @drbeefsupreme

Honestly there is probably a way to compile the glossary from some source documentation instead of doing it manually. The problem is that the rune entries and the stdlib entries in glossary.js _I wrote by hand_ since there was no metadata with this information we could just periodically scrape. I welcome that as part of this issue as well...
