### ISSUE TITLE
Search is hosed

### ISSUE THREAD

**Issue by ynx0** [urbit/urbit.org#594]
What it says on the tin. I seem the get the following console errors:
```js
Uncaught ReferenceError: tippy is not defined
    <anonymous> https://urbit.org/scripts.js:349
scripts.js:349:3
Uncaught ReferenceError: elasticlunr is not defined
    initSearch https://urbit.org/scripts.js:230
    <anonymous> https://urbit.org/scripts.js:334
    EventListener.handleEvent* https://urbit.org/scripts.js:333
scripts.js:230:15
Loading failed for the <script> with source “https://analytics.urbit.org/matomo.js”. runtime:1:1
```

![image](https://user-images.githubusercontent.com/9275716/114587489-b81c1980-9c53-11eb-98b9-4f2622604287.png)

**Comment by jalehman** [comment]
This probably got hosed due to the recent upgrade to Zola 0.13.0.

—

~wolref-podlex
https://urbit.org ( https://urbit.org/ )

**Comment by drbeefsupreme** [comment]
I was hoping this would be a simple revert until we figure out what about the new zola breaks search, but unfortunately it is not.

I made a revert PR for the docs PR here: https://github.com/urbit/docs/pull/1061
But when I try to make one for the urbit.org PR https://github.com/urbit/urbit.org/pull/588 GH says "Sorry, this pull request couldn’t be reverted automatically. It may have already been reverted, or the content may have changed since it was merged." Though I do not see any further helpful information as to what those changes may be.

Perhaps it is related to this? https://github.com/urbit/urbit.org/pull/589/commits/9828538c2d20895744ece28090dd435497eaaadb

But then if I revert that too, that PR breaks, and... then it is just turning into a mess where I'm worried that my lack of git-fu has a decent chance of leaving things in an even more confused state.
 
Obviously the real solution is to figure out what about the new version of zola broke search, but I don't know anything about zola beyond `zola serve` or what the new version does so I'm not the right person for that.

**Comment by tylershuster** [comment]
Give me a second, I might be able to fix this

**Comment by matildepark** [comment]
I found it I think, lol

— 
~haddef-sigwen
https://urbit.org

**Comment by tylershuster** [comment]
Do we just remove `{% if config.build_search_index %}`?
