### ISSUE TITLE
S3 Storage Setup: Link to, or include guides/video on how to set up an S3 bucket for DO, AWS, and min.io

### ISSUE THREAD

**Issue by urcades** [urbit/urbit.org#597]
Currently, on `https://urbit.org/using/os/s3/`, there is no listed guide for how to get S3 integrated into one's urbit.

Yesterday I attempted to explain to someone how to get S3 hooked up with AWS, and it was distinctly nightmarish. I know there are guides for this task scattered around, but we should spend the time to create very concise urbit-specific guides, given S3 bucket integration is our only real integration that makes an appearance in userspace, and one that is frequently asked about.

**Comment by eamsden** [comment]
I won't say we shouldn't document how to set it up with AWS, since people will try anyway, but almost every other hosting provider makes this easier. I have used S3 from DO but also Scaleway and Upcloud, all three are far easier than AWS. A warning that AWS in particular is a lot of effort and difficult to get right would not go amiss.

**Comment by matildepark** [comment]
https://operators.urbit.org/manual/os/s3
