### ISSUE TITLE
main text area of docs is too narrow

### ISSUE THREAD

**Issue by tinnus-napbus** [urbit/urbit.org#605]
The main text area column thingy is extremely narrow. This results in wrapping of a lot of codeblocks which makes them difficult to read.

Eg:

![2021-04-23_11h44m53s](https://user-images.githubusercontent.com/77721746/115798137-a2fc7300-a429-11eb-8ed7-defa2898f810.png)

Something approximately like this would be better:

![2021-04-23_11h51m44s](https://user-images.githubusercontent.com/77721746/115798443-5f563900-a42a-11eb-8384-f4bb27cf37e9.png)

**Comment by drbeefsupreme** [comment]
I noticed today this the formatting on this page is bad now - not sure when it happened. Maybe the update to the latest version of zola? https://urbit.org/docs/hoon/reference/auras/

I would try to fix it manually but since it was fine before and now it isn't, it would just be treating the symptom rather than the cause.

**Comment by tinnus-napbus** [comment]
I asked matilde and she said it's cos of this: https://github.com/urbit/urbit.org/blob/master/templates/sections/docs.html#L20

which seemingly comes from here: https://github.com/urbit/urbit.org/blob/master/sass/indigo.scss#L968

I played around and it seems it should be about 54em - 56em iirc. I dunno exactly where it should be modified though, probably not in the indigo css file? Probably in the docs.html template? I don't know FE stuff really

**Comment by matildepark** [comment]
> I noticed today this the formatting on this page is bad now - not sure when it happened. Maybe the update to the latest version of zola? https://urbit.org/docs/hoon/reference/auras/
> 
> I would try to fix it manually but since it was fine before and now it isn't, it would just be treating the symptom rather than the cause.

@drbeefsupreme That page's blocks look weird specifically because Zola's parser wraps code blocks in `<pre><code>` now, which has `white-space: pre-wrap`, which removes the scroll CSS. We could just make `pre code` undo that white-space declaration.

As for the _width_, that's from the `measure-wide` class, so you could just remove it, but then it becomes like, super duper wide. So, depends how wide you want it, @jalehman @tylershuster
