### ISSUE TITLE
In the age of dark mode, the favicon needs a white background

### ISSUE THREAD

**Issue by flowerornament** [urbit/urbit.org#89]
Favicon should be given a white background

**Comment by Fang-** [comment]
Github's favicon is all-black with no background. Do they suffer from a similar issue?

We get to choose the shape of the background still. I don't think a small white border would be on-brand, but we could consider a circular background instead of a square one. (No strong opinions here, just feel that square/no-transparency favicons are a bit meh.)

**Comment by galenwp** [comment]
I don't seem to get a favicon for urbit.org

**Comment by hardcodepunk** [comment]
> I don't seem to get a favicon for urbit.org

Your browser, OS and platform/device are?

**Comment by flowerornament** [comment]
@Fang- they do!

**Comment by flowerornament** [comment]
> I don't seem to get a favicon for urbit.org

Favicon loads for me on Firefox, Chrome, Safari

**Comment by alexmatz** [comment]
@msutherl what do you think about using the one we use for landscape?

**Comment by flowerornament** [comment]
@alexmatz hm, that one is actually not great and should probably be changed to match
